[global]
showWarningOnDirectExecution = true

[logger]
level = "info"

[runner]
magicEnabled = true

[server]
folderWatchBlacklist = []
headless = false  # Change to true for deployment
liveSave = false
runOnSave = false
port = 8501  # Change to 80 if needed, but may require admin permissions
enableCORS = true  # Recommended for security

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = true
serverPort = 8501
